def classes_en():
    dico = {
        0: "Speed limit (20km/h)",
        1: "Speed limit (30km/h)",
        2: "Speed limit (50km/h)",
        3: "Speed limit (60km/h)",
        4: "Speed limit (70km/h)",
        5: "Speed limit (80km/h)",
        6: "End of speed limit (80km/h)",
        7: "Speed limit (100km/h)",
        8: "Speed limit (120km/h)",
        9: "No passing",
        10: "No passing for vehicles over 3.5 metric tons",
        11: "Right-of-way at the next intersection",
        12: "Priority road",
        13: "Yield",
        14: "Stop",
        15: "No vehicles",
        16: "Vehicles over 3.5 metric tons prohibited",
        17: "No entry",
        18: "General caution",
        19: "Dangerous curve to the left",
        20: "Dangerous curve to the right",
        21: "Double curve",
        22: "Bumpy road",
        23: "Slippery road",
        24: "Road narrows on the right",
        25: "Road work",
        26: "Traffic signals",
        27: "Pedestrians",
        28: "Children crossing",
        29: "Bicycles crossing",
        30: "Beware of ice/snow",
        31: "Wild animals crossing",
        32: "End of all speed and passing limits",
        33: "Turn right ahead",
        34: "Turn left ahead",
        35: "Ahead only",
        36: "Go straight or right",
        37: "Go straight or left",
        38: "Keep right",
        39: "Keep left",
        40: "Roundabout mandatory",
        41: "End of no passing",
        42: "End of no passing by vehicles over 3.5 metric tons",
    }
    return dico

def classes_fr():
    dico = {
        0: "Limite de vitesse (20km/h)",
        1: "Limite de vitesse (30km/h)",
        2: "Limite de vitesse (50km/h)",
        3: "Limite de vitesse (60km/h)",
        4: "Limite de vitesse (70km/h)",
        5: "Limite de vitesse (80km/h)",
        6: "Fin de la limite de vitesse (80km/h)",
        7: "Limite de vitesse (100km/h)",
        8: "Limite de vitesse (120km/h)",
        9: "Interdiction de dépasser",
        10: "Interdiction de dépasser pour les véhicules lourds (3.5t)",
        11: "Priorité à droite",
        12: "Route prioritaire",
        13: "Cédez le passage",
        14: "Stop",
        15: "Interdiction de circuler",
        16: "Interdiction de circuler pour les véhicules lourds (3.5t)",
        17: "Interdiction d'entrer",
        18: "Attention",
        19: "Virage dangereux à gauche",
        20: "Virage dangereux à droite",
        21: "Double virage",
        22: "Route accidentée",
        23: "Route glissante",
        24: "Route étroite à droite",
        25: "Attention travaux",
        26: "Feu tricolore",
        27: "Attention piétons",
        28: "Attention enfants",
        29: "Cyclistes",
        30: "Attention, verglas",
        31: "Attention, animaux sauvages",
        32: "Fin de la limitation de vitesse et de la circulation",
        33: "Tournez à droite",
        34: "Tournez à gauche",
        35: "Tout droit",
        36: "Droite ou tout droit",
        37: "Gauche ou tout droit",
        38: "Continuer tout droit",
        39: "Continuer tout droit",
        40: "Circulation en rond-point",
        41: "Fin de l'interdiction de dépasser",
        42: "Fin de l'interdiction de dépasser pour les véhicules lourds (3.5t)",
    }
    return dico