def classes_en():
    dico = {
        0: "Speed limit (20km/h)",
        1: "Speed limit (30km/h)",
        2: "Speed limit (50km/h)",
        3: "Speed limit (60km/h)",
        4: "Speed limit (70km/h)",
        5: "Speed limit (80km/h)",
        6: "End of speed limit (80km/h)",
        7: "Speed limit (100km/h)",
        8: "Speed limit (120km/h)",
        9: "No passing",
        10: "No passing for vehicles over 3.5 metric tons",
        11: "Right-of-way at the next intersection",
        12: "Priority road",
        13: "Yield",
        14: "Stop",
        15: "No vehicles",
        16: "Vehicles over 3.5 metric tons prohibited",
        17: "No entry",
        18: "General caution",
        19: "Dangerous curve to the left",
        20: "Dangerous curve to the right",
        21: "Double curve",
        22: "Bumpy road",
        23: "Slippery road",
        24: "Road narrows on the right",
        25: "Road work",
        26: "Traffic signals",
        27: "Pedestrians",
        28: "Children crossing",
        29: "Bicycles crossing",
        30: "Beware of ice/snow",
        31: "Wild animals crossing",
        32: "End of all speed and passing limits",
        33: "Turn right ahead",
        34: "Turn left ahead",
        35: "Ahead only",
        36: "Go straight or right",
        37: "Go straight or left",
        38: "Keep right",
        39: "Keep left",
        40: "Roundabout mandatory",
        41: "End of no passing",
        42: "End of no passing by vehicles over 3.5 metric tons",
    }
    return dico

def classes_fr():
    dico = {
        0: "Limite de vitesse (20km/h)",
        1: "Limite de vitesse (30km/h)",
        2: "Limite de vitesse (50km/h)",
        3: "Limite de vitesse (60km/h)",
        4: "Limite de vitesse (70km/h)",
        5: "Limite de vitesse (80km/h)",
        6: "Fin de la limite de vitesse (80km/h)",
        7: "Limite de vitesse (100km/h)",
        8: "Limite de vitesse (120km/h)",
        9: "Interdiction de dépasser",
        10: "Interdiction de dépasser pour les véhicules lourds (3.5t)",
        11: "Priorité à droite",
        12: "Route prioritaire",
        13: "Cédez le passage",
        14: "Stop",
        15: "Interdiction de circuler",
        16: "Interdiction de circuler pour les véhicules lourds (3.5t)",
        17: "Interdiction d'entrer",
        18: "Attention",
        19: "Virage dangereux à gauche",
        20: "Virage dangereux à droite",
        21: "Double virage",
        22: "Route accidentée",
        23: "Route glissante",
        24: "Route étroite à droite",
        25: "Attention travaux",
        26: "Feu tricolore",
        27: "Attention piétons",
        28: "Attention enfants",
        29: "Cyclistes",
        30: "Attention, verglas",
        31: "Attention, animaux sauvages",
        32: "Fin de la limitation de vitesse et de la circulation",
        33: "Tournez à droite",
        34: "Tournez à gauche",
        35: "Tout droit",
        36: "Droite ou tout droit",
        37: "Gauche ou tout droit",
        38: "Continuer tout droit",
        39: "Continuer tout droit",
        40: "Circulation en rond-point",
        41: "Fin de l'interdiction de dépasser",
        42: "Fin de l'interdiction de dépasser pour les véhicules lourds (3.5t)",
    }
    return dico

def classes_EUD_en():
    dico = {
        0: "Courbe à droite",
        1: "Courbe à gauche",
        2: "Double courbure (gauche)",
        3: "Double virage (à droite)",
        4: "Rétrécissement de la chaussée (les deux)",
        5: "Rétrécissement de la chaussée (à droite)",
        6: "Route irrégulière (1 bosse)",
        7: "Route irrégulière (2 bosses)",
        8: "Route glissante",
        9: "Chute de pierres",
        10: "Passage pour piétons",
        11: "Enfants (école)",
        12: "Cyclistes entrant ou traversant",
        13: "Passage d'animaux sauvages",
        14: "Travaux routiers",
        15: "Signaux lumineux",
        16: "Intersection",
        17: "Intersection avec une route",
        18: "Rond-point",
        19: "Autres dangers",
        20: "Neige",
        21: "Cédez le passage",
        22: "Stop",
        23: "Route prioritaire",
        24: "Fin de la priorité",
        25: "Interdiction d'entrer",
        26: "Interdiction de tourner à gauche",
        27: "Interdiction de tourner à droite",
        28: "Dépassement interdit",
        29: "Limite de vitesse maximale 20",
        30: "Limite de vitesse maximale 30",
        31: "Limite de vitesse maximale 50",
        32: "Limite de vitesse maximale 80",
        33: "Limite de vitesse maximale 90",
        34: "Limite de vitesse maximale 100",
        35: "Limite de vitesse maximale 110",
        36: "Limite de vitesse maximale 120",
        37: "Dépassement sans arrêt interdit",
        38: "Fin de toutes les interdictions locales imposées aux véhicules en mouvement",
        39: "Fin de la limitation de vitesse maximale",
        40: "Fin de l'interdiction de dépasser",
        41: "Stationnement interdit",
        42: "Sens - Droit",
        43: "Sens - Droite",
        44: "Direction - Gauche",
        45: "Direction - droite ou droite",
        46: "Direction - Tout droit ou à gauche",
        47: "Direction - Tourner à droite",
        48: "Direction - Tourner à gauche",
        49: "Passer à droite",
        50: "Passer à gauche",
        51: "Rond-point obligatoire",
        52: "Piste cyclable obligatoire",
        53: "Piste cyclable obligatoire - chemin piétonnier",
        54: "Sens unique (droit)",
        55: "Début de la zone",
        56: "Fin de la zone",
        57: "Parking",
        58: "Arrêt de bus",
        59: "Route sans passage",
        60: "Transport de véhicules",
        61: "Distance par rapport au lieu",
        62: "Priorité à l'intersection",
        63: "Panneau supplémentaire",
        64: "Courbe à droite",
    }
    return dico

def classes_EUD_fr():
    dico = {
        0: "Courbe à droite",
        1: "Courbe à gauche",
        2: "Double courbure (gauche)",
        3: "Double virage (à droite)",
        4: "Rétrécissement de la chaussée (les deux)",
        5: "Rétrécissement de la chaussée (à droite)",
        6: "Route irrégulière (1 bosse)",
        7: "Route irrégulière (2 bosses)",
        8: "Route glissante",
        9: "Chute de pierres",
        10: "Passage pour piétons",
        11: "Enfants (école)",
        12: "Cyclistes entrant ou traversant",
        13: "Passage d'animaux sauvages",
        14: "Travaux routiers",
        15: "Signaux lumineux",
        16: "Intersection",
        17: "Intersection avec une route",
        18: "Rond-point",
        19: "Autres dangers",
        20: "Neige",
        21: "Cédez le passage",
        22: "Stop",
        23: "Route prioritaire",
        24: "Fin de la priorité",
        25: "Interdiction d'entrer",
        26: "Interdiction de tourner à gauche",
        27: "Interdiction de tourner à droite",
        28: "Dépassement interdit",
        29: "Limite de vitesse maximale 20",
        30: "Limite de vitesse maximale 30",
        31: "Limite de vitesse maximale 50",
        32: "Limite de vitesse maximale 80",
        33: "Limite de vitesse maximale 90",
        34: "Limite de vitesse maximale 100",
        35: "Limite de vitesse maximale 110",
        36: "Limite de vitesse maximale 120",
        37: "Dépassement sans arrêt interdit",
        38: "Fin de toutes les interdictions locales imposées aux véhicules en mouvement",
        39: "Fin de la limitation de vitesse maximale",
        40: "Fin de l'interdiction de dépasser",
        41: "Stationnement interdit",
        42: "Sens - Droit",
        43: "Sens - Droite",
        44: "Direction - Gauche",
        45: "Direction - droite ou droite",
        46: "Direction - Tout droit ou à gauche",
        47: "Direction - Tourner à droite",
        48: "Direction - Tourner à gauche",
        49: "Passer à droite",
        50: "Passer à gauche",
        51: "Rond-point obligatoire",
        52: "Piste cyclable obligatoire",
        53: "Piste cyclable obligatoire - chemin piétonnier",
        54: "Sens unique (droit)",
        55: "Début de la zone",
        56: "Fin de la zone",
        57: "Parking",
        58: "Arrêt de bus",
        59: "Route sans passage",
        60: "Transport de véhicules",
        61: "Distance par rapport au lieu",
        62: "Priorité à l'intersection",
        63: "Panneau supplémentaire",
        64: "Courbe à droite",
    }
    return dico


def classes_EUD_en_temp():
    """Dico, mais numero -1 par rapport au fichier original"""
    dico ={
        0: "Right bend",
        1: "Left bend",
        2: "Double bend (left)",
        3: "Double bend (right)",
        4: "Dangerous descent",
        5: "Steep ascent",
        6: "Carriageway narrows (both)",
        7: "Carriageway narrows (right)",
        8: "Carriageway narrows (left)",
        9: "Road leads on to quay or river bank",
        10: "Uneven road (1 bump)",
        11: "Uneven road (2 bump)",
        12: "Slippery road",
        13: "Loose gravel",
        14: "Falling rocks",
        15: "Pedestrian crossing",
        16: "Children (School)",
        17: "Cyclists entering or crossing",
        18: "Domestic animals crossing",
        19: "Wild animals crossing",
        20: "Road works",
        21: "Light signals",
        22: "Intersection",
        23: "Intersection with road",
        24: "Roundabout",
        25: "Two-way traffic",
        26: "Level-crossings with gates",
        27: "Other level-crossings",
        28: "Inmediate level-crossing",
        29: "Level-crossings additional signs",
        30: "Airfield",
        31: "Other dangers",
        32: "Snow",
        33: "Riders on horseback",
        34: "Give way",
        35: "Stop",
        36: "Priority road",
        37: "End of priority",
        38: "Priority for oncoming traffic",
        39: "Priority over oncoming traffic",
        40: "No entry",
        41: "Closed to all vehicles in both directions",
        42: "No entry for cycles",
        43: "No entry for vehicle drawing a trailer",
        44: "No entry for power driven vehicles",
        45: "No entry for vehicles having an overall widh exceeding … meters",
        46: "No entry for vehicles having an overall height exceeding … meters",
        47: "No entry for vehicles exceeding … tonnes laden mass",
        48: "No entry for vehicles having a mass exceeding … tonnes on one axle",
        49: "No entry for trucks",
        50: "No left turn",
        51: "No right turn",
        52: "No U-turn",
        53: "Overtaking prohibited",
        54: "Overtaking by goods vehicles prohibited",
        55: "Maximum speed limit 10",
        56: "Maximum speed limit 20",
        57: "Maximum speed limit 25",
        58: "Maximum speed limit 30",
        59: "Maximum speed limit 40",
        60: "Maximum speed limit 50",
        61: "Maximum speed limit 60",
        62: "Maximum speed limit 70",
        63: "Maximum speed limit 80",
        64: "Maximum speed limit 90",
        65: "Maximum speed limit 100",
        66: "Maximum speed limit 110",
        67: "Maximum speed limit 120",
        68: "Passing without stopping prohibited",
        69: "End of all local prohibitions imposed on moving vehicles",
        70: "End of maximum speed limit",
        71: "End of prohibition of overtaking",
        72: "End of prohibition of overtaking for goods vehicles",
        73: "Parking prohibited",
        74: "Parking prohibited (first half month)",
        75: "Parking prohibited (last half month)",
        76: "Standing and parking prohibited",
        77: "End of parking prohibited",
        78: "No photos",
        79: "Direction – Straight",
        80: "Direction – Right",
        81: "Direction – Left",
        82: "Direction – Straight or Right",
        83: "Direction – Straight or Left",
        84: "Direction – Turn right",
        85: "Direction – Turn left",
        86: "Pass Right",
        87: "Pass Left",
        88: "Pass Either side",
        89: "Compulsory roundabout",
        90: "Compulsory cycle track",
        91: "Compulsory footpath",
        92: "Compulsory cycle track - footpath",
        93: "Compulsory cycle track - footpath",
        94: "Compulsory bus",
        95: "End of compulsory bus",
        96: "End of compulsory cycle track",
        97: "End of pedestrian track",
        98: "Lanes reserved for certain vehicle type",
        99: "One-way (Straight)",
        100: "One-way (Right)",
        101: "One-way (Left)",
        102: "Motorway",
        103: "Road for motor vehicles",
        104: "Beginning of area",
        105: "End of area",
        106: "Maximum speed zone",
        107: "End of maximum speed zone",
        108: "Parking",
        109: "Parking",
        110: "Parking for handicap",
        111: "Parking for cars",
        112: "Parking for goods vehicles",
        113: "Parking for bus",
        114: "Parking on pavement or verge",
        115: "Parking on the right",
        116: "Parking on the left",
        117: "Parking garage",
        118: "Bus stop",
        119: "Cyclists-Pedestrians",
        120: "Cycle track",
        121: "Cyclists entering or crossing",
        122: "Residential area",
        123: "End of residential area",
        124: "Uneven road (1 bump)",
        125: "Pass right",
        126: "End of road works",
        127: "Filling station",
        128: "Hotel or motel",
        129: "Restaurant",
        130: "Refreshments or cafeteria",
        131: "Children on the road",
        132: "School patrol",
        133: "Water protection area",
        134: "River",
        135: "Road construction",
        136: "Police station",
        137: "Radio station",
        138: "Advance direction signs",
        139: "Direction to place",
        140: "Number and direction of traffic lanes",
        141: "Closure of a traffic lane",
        142: "No through road",
        143: "General speed limits",
        144: "Exit from motorway",
        145: "Carriage of vehicles",
        146: "Distance to place",
        147: "Length of dangerous section",
        148: "Intersection priority",
        149: "Ice/Snow",
        150: "Directional panel (arrows)",
        151: "Tram",
        152: "Car",
        153: "Bus",
        154: "Truck",
        155: "Handicap",
        156: "Bicycle",
        157: "Timing",
        158: "Supplemental panel",
        159: "Limited access on side",
        160: "Curve right",
        161: "Curve left",
        162: "Barrier",
        163: "Obstacle"
    }
    return dico

new = {0: 'Right bend', 1: 'Left bend', 2: 'Double bend (left)', 3: 'Double bend (right)', 4: 'Carriageway narrows (both)', 5: 'Carriageway narrows (right)', 6: 'Uneven road (1 bump)', 7: 'Uneven road (2 bump)', 8: 'Slippery road', 9: 'Falling rocks', 10: 'Pedestrian crossing', 11: 'Children (School)', 12: 'Cyclists entering or crossing', 13: 'Wild animals crossing', 14: 'Road works', 15: 'Light signals', 16: 'Intersection', 17: 'Intersection with road', 18: 'Roundabout', 19: 'Other dangers', 20: 'Snow', 21: 'Give way', 22: 'Stop', 23: 'Priority road', 24: 'End of priority', 25: 'No entry', 26: 'Closed to all vehicles in both directions', 27: 'No entry for vehicles exceeding … tonnes laden mass', 28: 'No entry for trucks', 29: 'No left turn', 30: 'No right turn', 31: 'Overtaking prohibited', 32: 'Overtaking by goods vehicles prohibited', 33: 'Maximum speed limit 20', 34: 'Maximum speed limit 30', 35: 'Maximum speed limit 40', 36: 'Maximum speed limit 50', 37: 'Maximum speed limit 60', 38: 'Maximum speed limit 70', 39: 'Maximum speed limit 80', 40: 'Maximum speed limit 90', 41: 'Maximum speed limit 100', 42: 'Maximum speed limit 110', 43: 'Maximum speed limit 120', 44: 'End of all local prohibitions imposed on moving vehicles', 45: 'End of maximum speed limit', 46: 'End of prohibition of overtaking', 47: 'End of prohibition of overtaking for goods vehicles', 48: 'Parking prohibited', 49: 'Standing and parking prohibited', 50: 'Direction – Straight', 51: 'Direction – Right', 52: 'Direction – Left', 53: 'Direction – Straight or Right', 54: 'Direction – Straight or Left', 55: 'Direction – Turn right', 56: 'Direction – Turn left', 57: 'Pass Right', 58: 'Pass Left', 59: 'Compulsory roundabout', 60: 'Compulsory cycle track', 61: 'Compulsory cycle track - footpath', 62: 'One-way (Straight)', 63: 'Beginning of area', 64: 'End of area', 65: 'Parking', 66: 'Parking', 67: 'Parking for cars', 68: 'Bus stop', 69: 'Advance direction signs', 70: 'Direction to place', 71: 'No through road', 72: 'Carriage of vehicles', 73: 'Distance to place', 74: 'Length of dangerous section', 75: 'Intersection priority', 76: 'Supplemental panel', 77: 'Limited access on side', 78: 'Curve right'}

#Avec anciens numeros
a_virer = [5, 6, 9, 10, 14, 19, 26, 27, 28, 29, 30, 31, 34, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 55, 56, 58, 60, 62, 63, 73, 75, 76, 77, 78, 79, 89, 92, 94, 95, 96, 97, 98, 99, 101, 102, 103, 104, 107, 108, 110, 111, 112, 113, 114, 115, 116, 117, 118, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 144, 145, 148, 150, 151, 152, 153, 154, 155, 156, 157, 158, 160, 162, 163, 164]
ancien_to_nouveau = {0: 0, 1: 1, 2: 2, 3: 3, 6: 4, 7: 5, 10: 6, 11: 7, 12: 8, 14: 9, 15: 10, 16: 11, 17: 12, 19: 13, 20: 14, 21: 15, 22: 16, 23: 17, 24: 18, 31: 19, 32: 20, 34: 21, 35: 22, 36: 23, 37: 24, 40: 25, 50: 26, 51: 27, 53: 28, 56: 29, 58: 30, 60: 31, 63: 32, 64: 33, 65: 34, 66: 35, 67: 36, 68: 37, 69: 38, 70: 39, 71: 40, 73: 41, 79: 42, 80: 43, 81: 44, 82: 45, 83: 46, 84: 47, 85: 48, 86: 49, 87: 50, 89: 51, 90: 52, 92: 53, 99: 54, 104: 55, 105: 56, 108: 57, 118: 58, 142: 59, 145: 60, 146: 61, 148: 62, 158: 63, 160: 64}

if __name__ == "__main__":

    #Genere les fonctions de decalage
    c = classes_EUD_en()
    new_mots = {}
    old_to_new = {}
    decalage = 0
    for i in range(163):
        if (i+1) in a_virer:
            decalage += 1
        else:
            new_mots[i - decalage] = c[i]
            old_to_new[i] = i - decalage
    print(new_mots)
    print(old_to_new)

